### ISSUE TITLE
Undefined in selected-items prevents suggestion list from rendering.

### ISSUE THREAD

**Issue by dotpointer** [Neovici/cosmoz-autocomplete#13]
The list of suggestions won't show if selected-items is filled with undefined.

Expected behaviour (in my opinion) is that the list should appear even if selected-items is unused.

Example:

// a function that returns undefined - {{ undefined }} is not enough here...
function returnsUndefined() {
	return undefined;
}

// some demo items - these should appear, but doesn't
demoItems = [{
		id: 'one',
		label: 'Red selection'
	}, {
		id: 'two',
		label: 'Blue selection'
	}];

<cosmoz-autocomplete
	items="[[ demoItems ]]"
	selected-items="{{ returnsUndefined(demoItems) }}">
</cosmoz-autocomplete>

**Comment by nomego** [comment]
Wow it feels like you really are abusing this component but I guess it should handle anything thrown at it :)

I took a look at the code and it starts out with a default 'sane' value of empty array (`[]`), which probably should be the "emptiest" it can be. `null` or `undefined` should probably not be valid values since it will cause a `.length` read to fail.
(What you're really doing is force-overriding the sane empty array value with an `undefined` value..)

Fortunately, we have an observer for `selectedItems`, so try replacing (around line 309 js):

```js
		selectedItemsChanged: function (items) {
			var item = null;
			if (items !== undefined && items !== null && Array.isArray(items) && items.length > 0) {
				item = items[0];
			}
```

with 

```js
		selectedItemsChanged: function (items) {
			if (items === undefined || items === null || !Array.isArray(items)) {
				this.selectedItems = [];
				return;
			}
			if (items.length === 0) {
				return;
			}
			var item = items[0];
```

Let me know if this fixes it.
Also, this should probably be fixed and have a test case with it.

**Comment by dotpointer** [comment]
Tested the fix implemented in a site and in a demo and it seems to work as requested.

Left to do here is a test case.

**Comment by nomego** [comment]
Is this still relevant in paper-autocomplete?
