### ISSUE TITLE
Memory leak: detached not called

### ISSUE THREAD

**Issue by megheaiulian** [Neovici/cosmoz-autocomplete#26]
cosmoz-autocomplete uses `Cosmoz.TranslatableBehavior` from `cosmoz-i18next` but the `detached` callback is not called and the instance remains in `translationElements`. 
Any element that is referenced by cosmoz-autocomplete gets stuck in memory.

**Comment by nomego** [comment]
Please focus on https://github.com/Neovici/cosmoz-frontend/issues/27 instead then

**Comment by plequang** [comment]
I think the problem is not in cosmoz-autocomplete, but in all elements implementing `Cosmoz.TranslatableBehavior` used in a `cosmoz-dialog`.
`cosmoz-dialog` instantiate it's template as soon as possible, but attached it to the dom only if open is called.
But Cosmoz.TranslatableBehaior register the element in `translationElements` during `created` callback.
So all translatable element in `cosmoz-dialog` that are never opened will never be detached (because not attached), but present in translationElements.
This cause detached DOM retention by the `dataHost` property of these elements.

**Comment by nomego** [comment]
Eek! `git blame` me! I switched from attached -> created in a guess-attempt to fix translations.

**Comment by megheaiulian** [comment]
Added PR Neovici/cosmoz-i18next#14

**Comment by megheaiulian** [comment]
Closing as the problem was in cosmoz-i18next.
